# Generated by Django 5.0.7 on 2026-08-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0002_alter_openentity_image_to_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='openentity',
            name='icon',
            field=models.CharField(blank=True, choices=[('', 'Automático (según el título)'), ('lightbulb', '💡 Iluminación / lámpara'), ('display', '🖥 Monitor / pantalla'), ('keyboard', '⌨ Teclado'), ('mouse', '🖱 Ratón'), ('mic', '🎙 Micrófono'), ('headphones', '🎧 Auriculares'), ('camera-video', '📹 Cámara / webcam'), ('usb-symbol', '🔌 Hub / adaptador USB'), ('plug', '🔋 Cable / cargador'), ('person-workspace', '🪑 Silla / escritorio'), ('laptop', '💻 Portátil'), ('pc-display', '🖲 Equipo de sobremesa'), ('device-hdd', '💾 Almacenamiento / SSD'), ('router', '📡 Router / red'), ('speaker', '🔊 Altavoces'), ('smartwatch', '⌚ Wearable'), ('phone', '📱 Móvil'), ('tablet', '📓 Tableta'), ('book', '📗 Libro'), ('mortarboard', '🎓 Curso / formación'), ('cup-hot', '☕ Café / escritorio'), ('tools', '🛠 Herramienta'), ('box-seam', '📦 Genérico')], help_text='Si lo dejas en automático, se deduce del título del gadget.', max_length=30, verbose_name='Icono'),
        ),
    ]
