# Generated by Django 5.0.7 on 2026-08-19 00:41

import django.utils.timezone
import portfolio.apps.pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(default=portfolio.apps.pipeline.models.generar_commit_hash, max_length=7, unique=True, verbose_name='Hash del commit')),
                ('visitor_name', models.CharField(max_length=24, verbose_name='Nombre del visitante')),
                ('visitor_location', models.CharField(blank=True, max_length=32, verbose_name='Ubicación')),
                ('message', models.CharField(blank=True, max_length=80, verbose_name='Mensaje de commit')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Duración del pipeline (ms)')),
                ('ip_hash', models.CharField(blank=True, max_length=32, verbose_name='Huella de IP')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible en el muro')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Deploy',
                'verbose_name_plural': 'Deploys',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='pipeline_de_created_a7862c_idx'), models.Index(fields=['ip_hash', '-created_at'], name='pipeline_de_ip_hash_0c9980_idx')],
            },
        ),
    ]
