# Generated by Django 5.0.7 on 2026-08-19 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='commit_type',
            field=models.CharField(choices=[('feat', 'feat'), ('fix', 'fix'), ('docs', 'docs'), ('refactor', 'refactor'), ('test', 'test'), ('chore', 'chore'), ('perf', 'perf'), ('style', 'style')], default='feat', max_length=10, verbose_name='Tipo de commit'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='visitor_location',
            field=models.CharField(blank=True, max_length=32, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='visitor_name',
            field=models.CharField(max_length=24, validators=[django.core.validators.RegexValidator(message='Usa solo letras, números, punto, guion o guion bajo. Sin espacios.', regex='^[a-zA-Z0-9._\\-]{2,24}$')], verbose_name='Autor del commit'),
        ),
    ]
