# Generated by Django 5.0.7 on 2026-08-21 15:06

import django.utils.timezone
import portfolio.apps.cielo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre')),
                ('location', models.CharField(blank=True, max_length=32, verbose_name='Lugar')),
                ('x', models.FloatField(help_text='Entre 0 y 1', verbose_name='Posición X')),
                ('y', models.FloatField(help_text='Entre 0 y 1', verbose_name='Posición Y')),
                ('magnitud', models.PositiveSmallIntegerField(default=portfolio.apps.cielo.models.magnitud_al_azar, verbose_name='Tamaño')),
                ('ip_hash', models.CharField(blank=True, max_length=32, verbose_name='Huella de IP')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible en el cielo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Encendida el')),
            ],
            options={
                'verbose_name': 'Estrella',
                'verbose_name_plural': 'Estrellas',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='cielo_star_created_46cb4f_idx'), models.Index(fields=['ip_hash', '-created_at'], name='cielo_star_ip_hash_8217a9_idx')],
            },
        ),
    ]
