# Generated by Django 5.2 on 2025-09-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('role', models.CharField(max_length=120, verbose_name='Rol/Título')),
                ('bio', models.CharField(max_length=300, verbose_name='Descripción breve')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='developers/', verbose_name='Avatar (imagen)')),
                ('avatar_url', models.URLField(blank=True, verbose_name='Avatar (URL)')),
                ('avatar_bg', models.CharField(blank=True, help_text='Sin #, ej: 4A90E2', max_length=6, verbose_name='Fondo avatar HEX')),
                ('avatar_text', models.CharField(blank=True, help_text='Sin #, ej: ffffff', max_length=6, verbose_name='Texto avatar HEX')),
                ('portfolio_url', models.URLField(verbose_name='URL del portafolio')),
                ('banner_name', models.SlugField(blank=True, help_text='Usado para data-banner-name y UTM content', max_length=120, verbose_name='Nombre de banner')),
                ('auto_utm', models.BooleanField(default=True, verbose_name='Agregar UTM automáticamente')),
                ('utm_source', models.CharField(blank=True, default='william_portfolio', max_length=60)),
                ('utm_medium', models.CharField(blank=True, default='banner', max_length=60)),
                ('utm_campaign', models.CharField(blank=True, default='dev_network', max_length=60)),
                ('skills', models.CharField(help_text='Separadas por coma, ej: React, TypeScript, Figma', max_length=240, verbose_name='Habilidades')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Desarrollador',
                'verbose_name_plural': 'Desarrolladores',
                'ordering': ['order', 'id'],
            },
        ),
    ]
