# Generated by Django 5.0.7 on 2025-09-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpenEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(max_length=240)),
                ('description', models.TextField(help_text='Puedes usar HTML básico para formato.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='open/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('keywords', models.ManyToManyField(blank=True, related_name='items', to='openapp.tag')),
            ],
            options={
                'verbose_name': 'Producto/Setup',
                'verbose_name_plural': 'Productos/Setups',
                'ordering': ['-created_at'],
            },
        ),
    ]
